APPIUM_SERVER=  'http://127.0.0.1:4723/wd/hub'
APPIUM_PLATFORM_VERSION=   '8.1'
APPIUM_PLATFORMNAME=     'Android'
APPIUM_DEVICE_NAME=   'Nexus 5 API 27'
APPIUM_PACKAGE_NAME=     'in.amazon.mShop.android.shopping'
APPIUM_ACTIVITY_NAME=  'com.amazon.micron.StartupActivity'