SIGN_IN="id=in.amazon.mShop.android.shopping:id/sign_in_button"
EMAIL_ID_TEXTFIELD="xpath=//android.webkit.WebView[@content-desc= 'Amazon Sign In']/android.view.View/android.view.View[2]/android.view.View[2]/android.view.View[2]/android.view.View/android.view.View/android.view.View[2]/android.widget.EditText"
CONTINUE_BTN="xpath=//android.widget.Button[@content-desc='Continue']"
EMAIL_PASSWORD="xpath=//android.webkit.WebView[@content-desc='Amazon Sign In']/android.view.View/android.view.View[5]/android.view.View[2]/android.widget.EditText"
LOGIN_BTN="xpath=//android.widget.Button[@content-desc='Login']"
LEFT_NAV_PANEL="xpath=//android.widget.ImageView[@content-desc='Navigation panel, button, double tap to open side panel']"
ERROR_PASSWORD="xpath=//android.view.View[@content-desc='Your password is incorrect']"
SEARCH="id=in.amazon.mShop.android.shopping:id/search_edit_text"
SEARCH_TEXT="id=in.amazon.mShop.android.shopping:id/search_auto_text"